name: SpacelifeCore
author: ProfessorSam
api-version: 1.19
version: ${project.version}
main: de.petropia.spacelifeCore.SpacelifeCore
depend:
  - "TurtleServer"
commands:
  spacelife:
    description: "Main admin command"
    aliases: "sl"
permissions:
  spacelife.command.spacelife.debug:
    default: false
    description: "Grant access for debugging"

