name: SpacelifeCore
author: ProfessorSam
api-version: 1.19
version: ${project.version}
main: de.petropia.spacelifeCore.SpacelifeCore
depend:
  - "TurtleServer"
commands:
  spacelife:
    description: "Main admin command"
    aliases: "sl"
  pay:
    description: "Pay money to a player"
  home:
    description: "Show players homes"
  balance:
    description: "Show your balance"
    aliases:
      - "kontostand"
      - "money"
  spawn:
    description: "teleport to spawn"
  workbench:
    description: "Open a workbench"
    aliases:
      - "w"
      - "craft"
      - "werkbank"
permissions:
  spacelife.command.spacelife.debug:
    default: false
    description: "Grant access for debugging"
  spacelife.command.spacelife.jump:
    default: false
    description: "Jump to another player"
  spacelife.command.spacelife.server:
    default: false
    description: "Change the server"
  spacelife.command.pay:
    default: true
    description: "Pay money to player"
  spacelife.command.balance.self:
    description: "View your own balance"
    default: true
  spacelife.command.balance.other:
    description: "Show balance of others"
  spacelife.command.spawn:
    description: "teleport to spawn"
    default: true
  spacelife.command.workbench:
    description: "Open a workbench"
    default: false
  spacelife.homes.5:
    description: "Allow 5 homes"
    default: false
  spacelife.homes.3:
    description: "Allow 3 homes"
    default: false
  spacelife.homes.2:
    description: "Allow 2 homes"
    default: true

