name: SpacelifeCore
author: ProfessorSam
api-version: 1.20
version: ${project.version}
main: de.petropia.spacelifeCore.SpacelifeCore
depend:
  - "TurtleServer"
commands:
  spacelife:
    description: "Main admin command"
    aliases: "sl"
  pay:
    description: "Pay money to a player"
  home:
    description: "Show players homes"
  balance:
    description: "Show your balance"
    aliases:
      - "kontostand"
      - "money"
  trash:
    description: "Throw items in the trash"
    aliases:
      - "müll"
  spawn:
    description: "teleport to spawn"
  workbench:
    description: "Open a workbench"
    aliases:
      - "w"
      - "craft"
      - "werkbank"
  tpa:
    description: "Teleport to a player"
  enderchest:
    description: "Opens your personal enderchests"
    aliases:
      - "ec"
  warp:
    description: "Show warps and teleport"
    aliases:
      - "warps"
  nightvision:
    description: "Give nightvision"
    aliases:
      - "nv"
      - "nachtsicht"
  fly:
    description: "Allow to fly"
    aliases:
      - "fliegen"
  hat:
    description: "Choose a hat"
    aliases:
      - "hut"
permissions:
  spacelife.command.spacelife.debug:
    default: false
    description: "Grant access for debugging"
  spacelife.command.spacelife.jump:
    default: false
    description: "Jump to another player"
  spacelife.command.spacelife.server:
    default: false
    description: "Change the server"
  spacelife.command.spacelife.addwarp:
    default: false
    description: "Add warp"
  spacelife.command.spacelife.removewarp:
    default: false
    description: "Remove a warp"
  spacelife.command.spacelife.blockInfo:
    default: false
    description: "Show Block info"
  spacelife.command.pay:
    default: true
    description: "Pay money to player"
  spacelife.command.balance.self:
    description: "View your own balance"
    default: true
  spacelife.command.balance.other:
    description: "Show balance of others"
  spacelife.command.spawn:
    description: "teleport to spawn"
    default: true
  spacelife.command.workbench:
    description: "Open a workbench"
    default: false
  spacelife.homes.5:
    description: "Allow 5 homes"
    default: false
  spacelife.homes.3:
    description: "Allow 3 homes"
    default: false
  spacelife.homes.2:
    description: "Allow 2 homes"
    default: true
  spacelife.command.tpa:
    description: "Tpa"
    default: true
  spacelife.command.trash:
    default: true
  spacelife.enderchest.standard:
    default: true
  spacelife.enderchest.premium:
    default: false
  spacelife.enderchest.premiumplus:
    default: false
  spacelife.command.enderchest.self:
    description: "View your own enderchest"
    default: false
  spacelife.command.enderchest.other:
    default: false
    description: "View the enderchest of someone else"
  spacelife.command.warp:
    description: "view warps"
    default: true
  spacelife.command.nightvision:
    description: "Nightvision command"
    default: false
  spacelife.command.fly:
    description: "fly on a server"
    default: false
  spacelife.command.hat:
    description: "set a hat"
    default: false